source/formulaforce/main/objects/Team__c/fields/Active_Since__c.field-meta.xml
<CustomField>
    <fullName>Active_Since__c</fullName>
    <label>Active Since</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

source/formulaforce/main/objects/Team__c/fields/Home_Base__c.field-meta.xml
<CustomField>
    <fullName>Home_Base__c</fullName>
    <description>deprecated - DO NOT USE</description>
    <label>Home Base (deprecated)</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

source/formulaforce/main/objects/Team__c/fields/Nationality__c.field-meta.xml
<CustomField>
    <fullName>Nationality__c</fullName>
    <description>deprecated - DO NOT USE</description>
    <label>Nationality (deprecated)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Austrian</fullName>
            </value>
            <value>
                <fullName>Brazilian</fullName>
            </value>
            <value>
                <fullName>British</fullName>
            </value>
            <value>
                <fullName>Dutch</fullName>
            </value>
            <value>
                <fullName>Finnish</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>Mexican</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>Italian</fullName>
            </value>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>Swiss</fullName>
            </value>
            <value>
                <fullName>American</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

source/formulaforce/main/objects/Team__c/fields/Team_Boss__c.field-meta.xml
<CustomField>
    <fullName>Team_Boss__c</fullName>
    <description>deprecated - DO NOT USE</description>
    <label>Team Boss (deprecated</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

source/formulaforce/main/objects/Team__c/fields/Testing_Distance__c.field-meta.xml
<CustomField>
    <fullName>Testing_Distance__c</fullName>
    <label>Testing Distance</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

source/formulaforce/main/classes/TeamsSelector.cls
public inherited sharing class TeamsSelector extends fflib_SObjectSelector {
	
	public List<Schema.SObjectField> getSObjectFieldList() {
		return new List<Schema.SObjectField> {
			Team__c.Id,
			Team__c.Name,
			Team__c.Testing_Distance__c,
            Team__c.Active_Since__c,
            Team__c.Home_Base__c,
            Team__c.Nationality__c,
            Team__c.Team_Boss__c
		};
	}

	public Schema.SObjectType getSObjectType() {
		return Team__c.sObjectType;
	}
}