source/formulaforce/main/objects/ChampionshipPoint__mdt/ChampionshipPoint__mdt.object-meta.xml
<CustomObject>
    <label>Championship Point</label>
    <pluralLabel>Championship Points</pluralLabel>
</CustomObject>

source/formulaforce/main/objects/ChampionshipPoint__mdt/fields/PointsAwarded__c.field-meta.xml
<CustomField>
    <fullName>PointsAwarded__c</fullName>
    <label>Points Awarded</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

source/formulaforce/main/objects/Contestant__c/Contestant__c.object-meta.xml
<CustomObject>
    <label>Contestant</label>
    <nameField>
        <displayFormat>CONTESTANT-{00000}</displayFormat>
        <label>Contestant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contestants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

source/formulaforce/main/objects/Contestant__c/fields/ChampionshipPoints__c.field-meta.xml
<CustomField>
    <fullName>ChampionshipPoints__c</fullName>
    <label>Championship Points</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

source/formulaforce/main/objects/Contestant__c/fields/RacePosition__c.field-meta.xml
<CustomField>
    <fullName>RacePosition__c</fullName>
    <label>Race Position</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

source/formulaforce/main/classes/ContestantService.cls
public class ContestantService {
    
    public static void awardChampionshipPoints(Set<Id> contestantIds) {

        // Apply championship points to selected contestants
        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        awardChampionshipPoints(uow, new ContestantsSelector().selectById(contestantIds));
        uow.commitWork();
    }

    public static void awardChampionshipPoints(fflib_ISObjectUnitOfWork uow, List<Contestant__c> contestants) {

        // Apply championship points to given contestants
        Map<Integer, ChampionshipPoint__mdt> pointsByTrackPosition = 
            new ChampionshipPointsSelector().selectAllByTrackPosition();
        for (Contestant__c contestant : contestants) {
            // determine points to award for given position
            ChampionshipPoint__mdt pointsForPostion = 
                pointsByTrackPosition.get(Integer.valueOf(contestant.RacePosition__c));
            if (pointsForPostion != null) {
                // Apply points and register for update with uow
                contestant.ChampionshipPoints__c = pointsForPostion.PointsAwarded__c;
                uow.registerDirty(contestant);
            }
        }
    }

    public static void retireFromRace(List<RaceRetirement> retirements) {
        throw new ContestantServiceException('Not implemented');
    }

    public class RaceRetirement {
        public Id contestantId;
        public String reason;
    }
}