source/formulaforce/main/objects/Circuit__c/Circuit__c.object-meta.xml
<CustomObject>
    <description>A Formula One Racing Circuit</description>
    <label>Circuit</label>
    <nameField>
        <label>Circuit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Circuits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

source/formulaforce/main/default/objects/Circuit__c/fields/Altitude__c.field-meta.xml
<CustomField>
    <fullName>Altitude__c</fullName>
    <description>Altitude (in metres) of circuit</description>
    <inlineHelpText>Altitude (in metres) of circuit</inlineHelpText>
    <label>Altitude (m)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

source/formulaforce/main/objects/Circuit__c/fields/Circuit_Location__c.field-meta.xml
<CustomField>
    <fullName>Circuit_Location__c</fullName>
    <description>Location of Circuit</description>
    <label>Circuit Location</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

source/formulaforce/main/default/objects/Circuit__c/fields/Circuit_Reference__c.field-meta.xml
<CustomField>
    <fullName>Circuit_Reference__c</fullName>
    <description>Unique Identifier for Circuit to act as an External Key - DO NO ALTER</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique Identifier for Circuit to act as an External Key - DO NO ALTER</inlineHelpText>
    <label>Circuit Reference</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

source/formulaforce/main/default/objects/Circuit__c/fields/Circuit_URL__c.field-meta.xml
<CustomField>
    <fullName>Circuit_URL__c</fullName>
    <description>Wikipedia Link for Circuit</description>
    <label>Circuit URL</label>
    <type>Url</type>
</CustomField>

source/formulaforce/main/objects/Circuit__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>The Country the Circuit is located in</description>
    <label>Country</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

source/formulaforce/main/default/objects/Circuit__c/fields/Data_Cloud_Id__c.field-meta.xml
<CustomField>
    <fullName>Data_Cloud_Id__c</fullName>
    <description>Unique Identifier to sync data with Data Cloud - DO NOT ALTER</description>
    <inlineHelpText>Unique Identifier to sync data with Data Cloud - DO NOT ALTER</inlineHelpText>
    <label>Data Cloud Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

source/formulaforce/main/objects/Circuit__c/fields/Driver_Nationality__c.field-meta.xml
<CustomField>
    <fullName>Driver_Nationality__c</fullName>
    <label>Driver Nationality</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

source/formulaforce/main/objects/Circuit__c/fields/Driver_Reference__c.field-meta.xml
<CustomField>
    <fullName>Driver_Reference__c</fullName>
    <label>Driver Reference</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

source/formulaforce/main/objects/Driver__c/Driver__c.object-meta.xml
<CustomObject>
    <label>Driver</label>
    <nameField>
        <label>Driver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

source/formulaforce/main/objects/Driver__c/fields/Driver_Code__c.field-meta.xml
<CustomField>
    <fullName>Driver_Code__c</fullName>
    <label>Driver Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

source/formulaforce/main/default/objects/Driver__c/fields/Driver_Number__c.field-meta.xml
<CustomField>
    <fullName>Driver_Number__c</fullName>
    <label>Driver Number</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

source/formulaforce/main/objects/Driver__c/fields/DriverId__c.field-meta.xml
<CustomField>
    <fullName>DriverId__c</fullName>
    <label>Driver Id</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

source/formulaforce/main/objects/Driver__c/fields/Nationality__c.field-meta.xml
<CustomField>
    <fullName>Nationality__c</fullName>
    <description>deprecated - DO NOT USE</description>
    <label>Nationality (deprecated)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brazilian</fullName>
            </value>
            <value>
                <fullName>British</fullName>
            </value>
            <value>
                <fullName>Finnish</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>Mexican</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>Dutch</fullName>
            </value>
            <value>
                <fullName>Austrian</fullName>
            </value>
            <value>
                <fullName>Monegasque</fullName>
            </value>
            <value>
                <fullName>Australian</fullName>
            </value>
            <value>
                <fullName>Chinese</fullName>
            </value>
            <value>
                <fullName>Canadian</fullName>
            </value>
            <value>
                <fullName>Danish</fullName>
            </value>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>Thai</fullName>
            </value>
            <value>
                <fullName>American</fullName>
            </value>
            <value>
                <fullName>Japanese</fullName>
            </value>
            <value>
                <fullName>New Zealand</fullName>
            </value>
            <value>
                <fullName>Italian</fullName>
            </value>
            <value>
                <fullName>Russian</fullName>
            </value>
            <value>
                <fullName>Swedish</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

source/formulaforce/main/objects/Driver__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>deprecated - DO NOT USE</description>
    <label>Team (deprecated)</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Drivers</relationshipLabel>
    <relationshipName>Drivers</relationshipName>
    <type>Lookup</type>
</CustomField>

source/formulaforce/main/objects/Season__c/Season__c.object-meta.xml
<CustomObject>
    <label>Season</label>
    <nameField>
        <label>Season Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

source/formulaforce/main/objects/Season__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <defaultValue>TEXT(YEAR(TODAY()))</defaultValue>
    <externalId>true</externalId>
    <label>Year</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

source/formulaforce/main/objects/Team__c/fields/Nationality__c.field-meta.xml
<CustomField>
    <fullName>Nationality__c</fullName>
    <description>deprecated - DO NOT USE</description>
    <label>Nationality (deprecated)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Austrian</fullName>
            </value>
            <value>
                <fullName>Brazilian</fullName>
            </value>
            <value>
                <fullName>British</fullName>
            </value>
            <value>
                <fullName>Dutch</fullName>
            </value>
            <value>
                <fullName>Finnish</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>Mexican</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>Italian</fullName>
            </value>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>Swiss</fullName>
            </value>
            <value>
                <fullName>American</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

source/formulaforce/main/default/objects/Team__c/fields/Team_Nationality__c.field-meta.xml
<CustomField>
    <fullName>Team_Nationality__c</fullName>
    <label>Team Nationality</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

source/formulaforce/main/objects/Team__c/fields/Team_Reference__c.field-meta.xml
<CustomField>
    <fullName>Team_Reference__c</fullName>
    <label>Team Reference</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

source/formulaforce/main/classes/F1DataCloudSyncService.cls
public with sharing class F1DataCloudSyncService {
    
    // sync F1 Circuits
    public static void syncCircuits() {

        List<F1_Circuit__dlm> dataCloudCircuits = new List<F1_Circuit__dlm>();
        List<Circuit__c> dataCloudCircuitsToUpsert = new List<Circuit__c>();

        // Get data from Data Cloud 
        dataCloudCircuits = [
            SELECT
                circuitid__c,
                circuitref__c,
                name__c,
                location__c,
                country__c,
                lat__c,
                lng__c,
                alt__c,
                url__c
            FROM F1_Circuit__dlm
        ];

        // Build list of Circuit objects to upsert
        if (dataCloudCircuits.size() > 0) {
            for (F1_Circuit__dlm f1Circuit : dataCloudCircuits) {
                Circuit__c newCircuit = new Circuit__c(
                    Data_Cloud_Id__c = Integer.valueOf(f1Circuit.circuitid__c).toString(),
                    Circuit_Reference__c = f1Circuit.circuitref__c,
                    name = f1Circuit.name__c,
                    Country__c = f1Circuit.country__c,
                    Circuit_Location__c = f1Circuit.location__c,
                    Circuit_Geo_Location__latitude__s = f1Circuit.lat__c,
                    Circuit_Geo_Location__longitude__s = f1Circuit.lng__c,
                    Altitude__c = f1Circuit.alt__c,
                    Circuit_URL__c = f1Circuit.url__c
                );
                dataCloudCircuitsToUpsert.add(newCircuit);
            }

            // perform the upsert
            F1DataCloudUpsertService.UpsertResult result = F1DataCloudUpsertService.upsertCircuits(dataCloudCircuitsToUpsert);
            System.Debug('Created: ' + result.recordsCreated + ' Updated: ' + result.recordsUpdated + ' Failed: ' + result.recordsFailed);
        } else {
            System.Debug('No Circuits returned from Data Cloud');
        }            
    }

    // sync F1 Teams (Constructors)
    public static void syncTeams() {

        List<F1_Constructor__dlm> dataCloudConstructors = new List<F1_Constructor__dlm>();
        List<Team__c> dataCloudConstructorsToUpsert = new List<Team__c>();

        // Get data from Data Cloud 
        dataCloudConstructors = [
            SELECT
                constructorid__c,
                constructorRef__c,
                name__c,
                nationality__c,
                url__c
            FROM F1_Constructor__dlm
        ];

        // Build list of Circuit objects to upsert
        if (dataCloudConstructors.size() > 0) {
            for (F1_Constructor__dlm f1Constructor : dataCloudConstructors) {
                Team__c newTeam = new Team__c(
                    Data_Cloud_Id__c = Integer.valueOf(f1Constructor.constructorid__c).toString(),
                    Team_Reference__c = f1Constructor.constructorRef__c,
                    name = f1Constructor.name__c,
                    Team_Nationality__c = f1Constructor.nationality__c,
                    URL__c = f1Constructor.url__c
                );
                dataCloudConstructorsToUpsert.add(newTeam);
            }

            // perform the upsert
            F1DataCloudUpsertService.UpsertResult result = F1DataCloudUpsertService.upsertTeams(dataCloudConstructorsToUpsert);
            System.Debug('Created: ' + result.recordsCreated + ' Updated: ' + result.recordsUpdated + ' Failed: ' + result.recordsFailed);
        } else {
            System.Debug('No Constructors returned from Data Cloud');
        }            
    }

    // sync Seasons
    public static void syncSeasons() {

        List<F1_Season__dlm> dataCloudSeasons = new List<F1_Season__dlm>();
        List<Season__c> dataCloudSeasonsToUpsert = new List<Season__c>();

        // Get data from Data Cloud 
        dataCloudSeasons = [
            SELECT
                year__c,
                url__c
            FROM F1_Season__dlm
        ];

        // Build list of Circuit objects to upsert
        if (dataCloudSeasons.size() > 0) {
            for (F1_Season__dlm f1Season : dataCloudSeasons) {
                Season__c newSeason = new Season__c(
                    Year__c = Integer.valueOf(f1Season.year__c).toString(),
                    name = Integer.valueOf(f1Season.year__c).toString() + ' Formula 1 Season',
                    URL__c = f1Season.url__c
                );
                dataCloudSeasonsToUpsert.add(newSeason);
            }

            // perform the upsert
            F1DataCloudUpsertService.UpsertResult result = F1DataCloudUpsertService.upsertSeasons(dataCloudSeasonsToUpsert);
            System.Debug('Created: ' + result.recordsCreated + ' Updated: ' + result.recordsUpdated + ' Failed: ' + result.recordsFailed);
        } else {
            System.Debug('No Seasons returned from Data Cloud');
        }            
    }

    // sync F1 Drivers
    public static void syncDrivers() {

        List<F1_Driver__dlm> dataCloudDrivers = new List<F1_Driver__dlm>();
        List<Driver__c> dataCloudDriversToUpsert = new List<Driver__c>();

        // Get data from Data Cloud 
        dataCloudDrivers = [
            SELECT
                code__c,
                dob__c,
                driverid__c,
                driverRef__c,
                forename__c,
                nationality__c,
                number__c,
                surname__c,
                url__c
            FROM F1_Driver__dlm
        ];

        // Build list of Driver objects to upsert
        if (dataCloudDrivers.size() > 0) {
            for (F1_Driver__dlm f1Driver : dataCloudDrivers) {
                Driver__c newDriver = new Driver__c(
                    Data_Cloud_Id__c = Integer.valueOf(f1Driver.driverid__c).toString(),
                    Date_of_Birth__c = f1Driver.dob__c,
                    Driver_Code__c = f1Driver.code__c,
                    Driver_Reference__c = f1Driver.driverRef__c,
                    name = f1Driver.forename__c + ' ' + f1Driver.surname__c,
                    Driver_Nationality__c = f1Driver.nationality__c,
                    Driver_Number__c = (f1Driver.number__c != null) ? Integer.valueOf(f1Driver.number__c).toString() : '',
                    URL__c = f1Driver.url__c
                );
                dataCloudDriversToUpsert.add(newDriver);
            }

            // perform the upsert
            F1DataCloudUpsertService.UpsertResult result = F1DataCloudUpsertService.upsertDrivers(dataCloudDriversToUpsert);
            System.Debug('Created: ' + result.recordsCreated + ' Updated: ' + result.recordsUpdated + ' Failed: ' + result.recordsFailed);
        } else {
            System.Debug('No Constructors returned from Data Cloud');
        }            
    }
}