source/formulaforce/main/objects/Contestant__c/Contestant__c.object-meta.xml
<CustomObject>
    <label>Contestant</label>
    <nameField>
        <displayFormat>CONTESTANT-{00000}</displayFormat>
        <label>Contestant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contestants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

source/formulaforce/main/objects/Contestant__c/fields/Car_Number__c.field-meta.xml
<CustomField>
    <fullName>Car_Number__c</fullName>
    <label>Car Number</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

source/formulaforce/main/objects/Contestant__c/fields/ChampionshipPoints__c.field-meta.xml
<CustomField>
    <fullName>ChampionshipPoints__c</fullName>
    <label>Championship Points</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

source/formulaforce/main/objects/Contestant__c/fields/Data_Cloud_Id__c.field-meta.xml
<CustomField>
    <fullName>Data_Cloud_Id__c</fullName>
    <externalId>true</externalId>
    <label>Data Cloud Id</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

source/formulaforce/main/objects/Contestant__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Driver</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only Active Drivers can be Contestants in a Race</errorMessage>
        <filterItems>
            <field>Driver__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Only Drivers whose status is active are permitted</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Contestants</relationshipLabel>
    <relationshipName>Contestants</relationshipName>
    <type>Lookup</type>
</CustomField>

source/formulaforce/main/objects/Contestant__c/fields/Driver_Number__c.field-meta.xml
<CustomField>
    <fullName>Driver_Number__c</fullName>
    <label>Driver Number</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

source/formulaforce/main/objects/Contestant__c/fields/Fastest_Lap__c.field-meta.xml
<CustomField>
    <fullName>Fastest_Lap__c</fullName>
    <label>Fastest Lap</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

source/formulaforce/main/objects/Contestant__c/fields/Fastest_Lap_Speed__c.field-meta.xml
<CustomField>
    <fullName>Fastest_Lap_Speed__c</fullName>
    <label>Fastest Lap Speed</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

source/formulaforce/main/objects/Contestant__c/fields/Fastest_Lap_Time__c.field-meta.xml
<CustomField>
    <fullName>Fastest_Lap_Time__c</fullName>
    <label>Fastest Lap Time</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

source/formulaforce/main/objects/Contestant__c/fields/Finishing_Status__c.field-meta.xml
<CustomField>
    <fullName>Finishing_Status__c</fullName>
    <label>Finishing Status</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

source/formulaforce/main/objects/Contestant__c/fields/GridPosition__c.field-meta.xml
<CustomField>
    <fullName>GridPosition__c</fullName>
    <label>Grid Position</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

source/formulaforce/main/objects/Contestant__c/fields/Laps_Completed__c.field-meta.xml
<CustomField>
    <fullName>Laps_Completed__c</fullName>
    <label>Laps Completed</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

source/formulaforce/main/objects/Contestant__c/fields/Race__c.field-meta.xml
<CustomField>
    <fullName>Race__c</fullName>
    <label>Race</label>
    <referenceTo>Race__c</referenceTo>
    <relationshipLabel>Contestants</relationshipLabel>
    <relationshipName>Contestants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

source/formulaforce/main/objects/Contestant__c/fields/Race_Position_Order__c.field-meta.xml
<CustomField>
    <fullName>Race_Position_Order__c</fullName>
    <label>Race Position Order</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

source/formulaforce/main/objects/Contestant__c/fields/Race_Position_Text__c.field-meta.xml
<CustomField>
    <fullName>Race_Position_Text__c</fullName>
    <label>Race Position (Text)</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

source/formulaforce/main/objects/Contestant__c/fields/Race_Round__c.field-meta.xml
<CustomField>
    <fullName>Race_Round__c</fullName>
    <label>Race Round</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

source/formulaforce/main/objects/Contestant__c/fields/Race_Season__c.field-meta.xml
<CustomField>
    <fullName>Race_Season__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Race Season</label>
    <referenceTo>Season__c</referenceTo>
    <relationshipLabel>Contestants</relationshipLabel>
    <relationshipName>Contestants</relationshipName>
    <type>Lookup</type>
</CustomField>

source/formulaforce/main/objects/Contestant__c/fields/RacePosition__c.field-meta.xml
<CustomField>
    <fullName>RacePosition__c</fullName>
    <label>Race Position</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

source/formulaforce/main/objects/Contestant__c/fields/RaceTime__c.field-meta.xml
<CustomField>
    <fullName>RaceTime__c</fullName>
    <label>Race Time (ms)</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

source/formulaforce/main/objects/Contestant__c/fields/Season__c.field-meta.xml
<CustomField>
    <fullName>Season__c</fullName>
    <description>deprecated - DO NOT USE</description>
    <formula>Race__r.Season__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Season (deprecated)</label>
    <type>Text</type>
</CustomField>

source/formulaforce/main/objects/Contestant__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Contestants</relationshipLabel>
    <relationshipName>Contestants</relationshipName>
    <type>Lookup</type>
</CustomField>

source/formulaforce/main/objects/Driver__c/Driver__c.object-meta.xml
<CustomObject>
    <label>Driver</label>
    <nameField>
        <label>Driver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

source/formulaforce/main/default/objects/Driver__c/fields/Driver_Number__c.field-meta.xml
<CustomField>
    <fullName>Driver_Number__c</fullName>
    <label>Driver Number</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

source/formulaforce/main/objects/Driver__c/fields/DriverId__c.field-meta.xml
<CustomField>
    <fullName>DriverId__c</fullName>
    <label>Driver Id</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

source/formulaforce/main/objects/Driver__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>deprecated - DO NOT USE</description>
    <label>Team (deprecated)</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Drivers</relationshipLabel>
    <relationshipName>Drivers</relationshipName>
    <type>Lookup</type>
</CustomField>

source/formulaforce/main/objects/Race__c/Race__c.object-meta.xml
<CustomObject>
    <label>Race</label>
    <nameField>
        <label>Race Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Races</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

source/formulaforce/main/objects/Race__c/fields/Season__c.field-meta.xml
<CustomField>
    <fullName>Season__c</fullName>
    <label>Season</label>
    <referenceTo>Season__c</referenceTo>
    <relationshipLabel>Races</relationshipLabel>
    <relationshipName>Races</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

source/formulaforce/main/objects/Race__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <description>deprecated - DO NOT USE</description>
    <formula>Season__r.Year__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Year (deprecated)</label>
    <type>Text</type>
</CustomField>

source/formulaforce/main/objects/Season__c/Season__c.object-meta.xml
<CustomObject>
    <label>Season</label>
    <nameField>
        <label>Season Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

source/formulaforce/main/objects/Season__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <defaultValue>TEXT(YEAR(TODAY()))</defaultValue>
    <externalId>true</externalId>
    <label>Year</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

source/formulaforce/main/classes/F1DataCloudSyncContestantsBatch.cls
/**
 * Batch class for processing large upsert operations
 */
public class F1DataCloudSyncContestantsBatch implements Database.Batchable<SObject>, Database.Stateful {
    
    private List<SObject> recordsToProcess;
    private F1DataCloudUpsertService.UpsertConfig config;
    private List<F1DataCloudUpsertService.UpsertResult> batchResults;
    
    public F1DataCloudSyncContestantsBatch(List<SObject> records, F1DataCloudUpsertService.UpsertConfig upsertConfig) {
        this.recordsToProcess = records;
        this.config = upsertConfig;
        this.batchResults = new List<F1DataCloudUpsertService.UpsertResult>();
    }
    
    public Iterable<SObject> start(Database.BatchableContext BC) {
        /*string query = 'SELECT ' +
                        'constructorid__c, driverid__c, fastestlap__c, fastestlapspeed__c, fastestlaptime__c, ' +
                        'finishing_status__c, grid__c, laps__c, milliseconds__c, number__c, points__c,' +
                        'position__c, positionorder__c, positiontext__c, raceid__c, race_round__c, race_year__c, ' +
                        'resultid__c FROM F1_Race_Result__dlm';
        return Database.getQueryLocator(query);*/
        return recordsToProcess;
    }
    
    public void execute(Database.BatchableContext BC, List<SObject> batch) {

        List<F1_Race_Result__dlm> dataCloudRaceResults = new List<F1_Race_Result__dlm>();
        List<Contestant__c> dataCloudContestantsToUpsert = new List<Contestant__c>();

        dataCloudRaceResults.addAll((List<F1_Race_Result__dlm>)batch);
        
        // convert to contestant records
        for (F1_Race_Result__dlm f1RaceResult : dataCloudRaceResults) {
                Contestant__c newContestant = new Contestant__c(
                    Data_Cloud_Id__c = Integer.valueOf(f1RaceResult.resultid__c).toString(),
                    Car_Number__c = (f1RaceResult.number__c != null) ? Integer.valueOf(f1RaceResult.number__c).toString() : '',
                    ChampionshipPoints__c = f1RaceResult.points__c,
                    Driver_Number__c = f1RaceResult.number__c,
                    Fastest_Lap__c = f1RaceResult.fastestlap__c,
                    Fastest_Lap_Speed__c = f1RaceResult.fastestlapspeed__c,
                    Fastest_Lap_Time__c = f1RaceResult.fastestlaptime__c,
                    Finishing_Status__c = f1RaceResult.finishing_status__c,
                    GridPosition__c = f1RaceResult.grid__c,
                    Laps_Completed__c = f1RaceResult.laps__c,
                    RacePosition__c = f1RaceResult.position__c,
                    Race_Position_Text__c = f1RaceResult.positiontext__c,
                    Race_Position_Order__c = f1RaceResult.positionorder__c,
                    Race_Round__c = f1RaceResult.race_round__c,
                    RaceTime__c = f1RaceResult.milliseconds__c
                );
                
                // Link to existing Driver using External ID relationship
                if(!String.isBlank(Integer.valueOf(f1RaceResult.driverId__c).toString())) {
                    Driver__c driver = new Driver__c();
                    driver.Data_Cloud_Id__c = Integer.valueOf(f1RaceResult.driverid__c).toString();
                    newContestant.Driver__r = driver; // This creates the relationship link
                }
                // Link to existing Race using External ID relationship
                if(!String.isBlank(Integer.valueOf(f1RaceResult.raceid__c).toString())) {
                    Race__c race = new Race__c();
                    race.Data_Cloud_Id__c = Integer.valueOf(f1RaceResult.raceid__c).toString();
                    newContestant.Race__r = race; // This creates the relationship link
                }
                // Link to existing Season using External ID relationship
                if(!String.isBlank(Integer.valueOf(f1RaceResult.race_year__c).toString())) {
                    Season__c season = new Season__c();
                    season.Year__c = Integer.valueOf(f1RaceResult.race_year__c).toString();
                    newContestant.Race_Season__r = season; // This creates the relationship link
                }
                // Link to existing Team using External ID relationship
                if(!String.isBlank(Integer.valueOf(f1RaceResult.constructorid__c).toString())) {
                    Team__c team = new Team__c();
                    team.Data_Cloud_Id__c = Integer.valueOf(f1RaceResult.constructorid__c).toString();
                    newContestant.Team__r = team; // This creates the relationship link
                }
                dataCloudContestantsToUpsert.add(newContestant);
        }

        // prepare and upsert contestant records
        List<SObject> records = new List<SObject>();
        records.addAll(dataCloudContestantsToUpsert);

        F1DataCloudUpsertService.UpsertResult result = F1DataCloudUpsertService.upsertRecords(records, config);
        batchResults.add(result);
        
        System.debug('Batch processed: ' + result.recordsCreated + ' created, ' + 
                    result.recordsUpdated + ' updated, ' + result.recordsFailed + ' failed');
    }
    
    public void finish(Database.BatchableContext BC) {
        // Summarize results
        Integer totalCreated = 0;
        Integer totalUpdated = 0;
        Integer totalFailed = 0;
        
        for (F1DataCloudUpsertService.UpsertResult result : batchResults) {
            totalCreated += result.recordsCreated;
            totalUpdated += result.recordsUpdated;
            totalFailed += result.recordsFailed;
        }
        
        System.debug('Contestant Batch upsert completed - Created: ' + totalCreated + 
                    ', Updated: ' + totalUpdated + ', Failed: ' + totalFailed);
        
        // Send notification email if needed
        if (totalFailed > 0) {
            sendErrorNotification(totalFailed);
        }
    }
    
    private void sendErrorNotification(Integer failedRecords) {
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
        email.setToAddresses(new String[]{'stephenmoss@brooke.global'});
        email.setSubject('Contestant Batch Upsert Errors Detected');
        email.setPlainTextBody('The contestant batch upsert operation completed with ' + failedRecords + ' failed records.');
        
        Messaging.sendEmail(new Messaging.SingleEmailMessage[]{email});
    }
}