source/formulaforce/main/objects/Contestant__c/Contestant__c.object-meta.xml
<CustomObject>
    <label>Contestant</label>
    <nameField>
        <displayFormat>CONTESTANT-{00000}</displayFormat>
        <label>Contestant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contestants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

source/formulaforce/main/objects/Contestant__c/fields/Car_Number__c.field-meta.xml
<CustomField>
    <fullName>Car_Number__c</fullName>
    <label>Car Number</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

source/formulaforce/main/objects/Contestant__c/fields/ChampionshipPoints__c.field-meta.xml
<CustomField>
    <fullName>ChampionshipPoints__c</fullName>
    <label>Championship Points</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

source/formulaforce/main/objects/Contestant__c/fields/DNF__c.field-meta.xml
<CustomField>
    <fullName>DNF__c</fullName>
    <defaultValue>false</defaultValue>
    <description>deprecated - DO NOT USE</description>
    <label>DNF (deprecated)</label>
    <type>Checkbox</type>
</CustomField>

source/formulaforce/main/objects/Contestant__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Driver</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only Active Drivers can be Contestants in a Race</errorMessage>
        <filterItems>
            <field>Driver__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Only Drivers whose status is active are permitted</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Contestants</relationshipLabel>
    <relationshipName>Contestants</relationshipName>
    <type>Lookup</type>
</CustomField>

source/formulaforce/main/objects/Contestant__c/fields/Laps_Completed__c.field-meta.xml
<CustomField>
    <fullName>Laps_Completed__c</fullName>
    <label>Laps Completed</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

source/formulaforce/main/objects/Contestant__c/fields/Qualification1LapTime__c.field-meta.xml
<CustomField>
    <fullName>Qualification1LapTime__c</fullName>
    <description>deprecated - DO NOT USE</description>
    <label>Qualification 1 Lap Time (deprecated)</label>
    <precision>9</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

source/formulaforce/main/objects/Contestant__c/fields/Qualification2LapTime__c.field-meta.xml
<CustomField>
    <fullName>Qualification2LapTime__c</fullName>
    <description>deprecated - DO NOT USE</description>
    <label>Qualification 2 Lap Time (deprecated)</label>
    <precision>9</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

source/formulaforce/main/objects/Contestant__c/fields/Qualification3LapTime__c.field-meta.xml
<CustomField>
    <fullName>Qualification3LapTime__c</fullName>
    <description>deprecated - DO NOT USE</description>
    <label>Qualification 3 Lap Time (deprecated)</label>
    <precision>9</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

source/formulaforce/main/objects/Contestant__c/fields/Race__c.field-meta.xml
<CustomField>
    <fullName>Race__c</fullName>
    <label>Race</label>
    <referenceTo>Race__c</referenceTo>
    <relationshipLabel>Contestants</relationshipLabel>
    <relationshipName>Contestants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

source/formulaforce/main/objects/Contestant__c/fields/RacePosition__c.field-meta.xml
<CustomField>
    <fullName>RacePosition__c</fullName>
    <label>Race Position</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

source/formulaforce/main/objects/Contestant__c/fields/Season__c.field-meta.xml
<CustomField>
    <fullName>Season__c</fullName>
    <description>deprecated - DO NOT USE</description>
    <formula>Race__r.Season__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Season (deprecated)</label>
    <type>Text</type>
</CustomField>

source/formulaforce/main/objects/Contestant__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Contestants</relationshipLabel>
    <relationshipName>Contestants</relationshipName>
    <type>Lookup</type>
</CustomField>

source/formulaforce/main/objects/Driver__c/Driver__c.object-meta.xml
<CustomObject>
    <label>Driver</label>
    <nameField>
        <label>Driver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

source/formulaforce/main/objects/Driver__c/fields/DriverId__c.field-meta.xml
<CustomField>
    <fullName>DriverId__c</fullName>
    <label>Driver Id</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

source/formulaforce/main/objects/Driver__c/fields/FIA_Super_License__c.field-meta.xml
<CustomField>
    <fullName>FIA_Super_License__c</fullName>
    <defaultValue>false</defaultValue>
    <description>deprecated - DO NOT USE</description>
    <label>FIA Super License (deprecated)</label>
    <type>Checkbox</type>
</CustomField>

source/formulaforce/main/objects/Driver__c/fields/Nationality__c.field-meta.xml
<CustomField>
    <fullName>Nationality__c</fullName>
    <description>deprecated - DO NOT USE</description>
    <label>Nationality (deprecated)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brazilian</fullName>
            </value>
            <value>
                <fullName>British</fullName>
            </value>
            <value>
                <fullName>Finnish</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>Mexican</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>Dutch</fullName>
            </value>
            <value>
                <fullName>Austrian</fullName>
            </value>
            <value>
                <fullName>Monegasque</fullName>
            </value>
            <value>
                <fullName>Australian</fullName>
            </value>
            <value>
                <fullName>Chinese</fullName>
            </value>
            <value>
                <fullName>Canadian</fullName>
            </value>
            <value>
                <fullName>Danish</fullName>
            </value>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>Thai</fullName>
            </value>
            <value>
                <fullName>American</fullName>
            </value>
            <value>
                <fullName>Japanese</fullName>
            </value>
            <value>
                <fullName>New Zealand</fullName>
            </value>
            <value>
                <fullName>Italian</fullName>
            </value>
            <value>
                <fullName>Russian</fullName>
            </value>
            <value>
                <fullName>Swedish</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

source/formulaforce/main/objects/Driver__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>deprecated - DO NOT USE</description>
    <label>Team (deprecated)</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Drivers</relationshipLabel>
    <relationshipName>Drivers</relationshipName>
    <type>Lookup</type>
</CustomField>

source/formulaforce/main/objects/Driver__c/fields/TwitterHandle__c.field-meta.xml
<CustomField>
    <fullName>TwitterHandle__c</fullName>
    <description>deprecated - DO NOT USE</description>
    <label>Twitter Handle (deprecated)</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

source/formulaforce/main/objects/Race__c/Race__c.object-meta.xml
<CustomObject>
    <label>Race</label>
    <nameField>
        <label>Race Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Races</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

source/formulaforce/main/objects/Race__c/fields/Race_Date__c.field-meta.xml
<CustomField>
    <fullName>Race_Date__c</fullName>
    <label>Race Date</label>
    <type>Date</type>
</CustomField>

source/formulaforce/main/objects/Race__c/fields/Round__c.field-meta.xml
<CustomField>
    <fullName>Round__c</fullName>
    <label>Round</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

source/formulaforce/main/objects/Race__c/fields/Season__c.field-meta.xml
<CustomField>
    <fullName>Season__c</fullName>
    <label>Season</label>
    <referenceTo>Season__c</referenceTo>
    <relationshipLabel>Races</relationshipLabel>
    <relationshipName>Races</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

source/formulaforce/main/objects/Race__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status (deprecated)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Red Flagged</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

source/formulaforce/main/objects/Race__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <description>deprecated - DO NOT USE</description>
    <formula>Season__r.Year__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Year (deprecated)</label>
    <type>Text</type>
</CustomField>

source/formulaforce/main/objects/Season__c/Season__c.object-meta.xml
<CustomObject>
    <label>Season</label>
    <nameField>
        <label>Season Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

source/formulaforce/main/objects/Season__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <defaultValue>TEXT(YEAR(TODAY()))</defaultValue>
    <externalId>true</externalId>
    <label>Year</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

source/formulaforce/main/objects/Team__c/fields/Active_Since__c.field-meta.xml
<CustomField>
    <fullName>Active_Since__c</fullName>
    <label>Active Since</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

source/formulaforce/main/objects/Team__c/fields/Home_Base__c.field-meta.xml
<CustomField>
    <fullName>Home_Base__c</fullName>
    <description>deprecated - DO NOT USE</description>
    <label>Home Base (deprecated)</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

source/formulaforce/main/objects/Team__c/fields/Nationality__c.field-meta.xml
<CustomField>
    <fullName>Nationality__c</fullName>
    <description>deprecated - DO NOT USE</description>
    <label>Nationality (deprecated)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Austrian</fullName>
            </value>
            <value>
                <fullName>Brazilian</fullName>
            </value>
            <value>
                <fullName>British</fullName>
            </value>
            <value>
                <fullName>Dutch</fullName>
            </value>
            <value>
                <fullName>Finnish</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>Mexican</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>Italian</fullName>
            </value>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>Swiss</fullName>
            </value>
            <value>
                <fullName>American</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

source/formulaforce/main/objects/Team__c/fields/Team_Boss__c.field-meta.xml
<CustomField>
    <fullName>Team_Boss__c</fullName>
    <description>deprecated - DO NOT USE</description>
    <label>Team Boss (deprecated</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

source/formulaforce/main/objects/Team__c/fields/Team_Id__c.field-meta.xml
<CustomField>
    <fullName>Team_Id__c</fullName>
    <description>deprecated - DO NOT USE</description>
    <label>Team Id (deprecated)</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

source/formulaforce/main/classes/SeasonService.cls
public with sharing class SeasonService {
    
    public static void issueNewsLetterCurrentSeason() {
		throw new SeasonServiceException('Not implemented');
	}
	
	public static void issueNewsLetters(Set<Id> seasonIds) {
		throw new SeasonServiceException('Not implemented');		
	}

	public static void updateStandings(Set<Id> seasonIds) {
		throw new SeasonServiceException('Not implemented');
	}

	public static void updateStandings(List<UpdateStandings> updateStandings) {
		throw new SeasonServiceException('Not implemented');
	}

    public static void importSeasons(String jsonData) {
		// Parse JSON data
		System.debug(jsonData);
		SeasonsData seasonsData = 
			(SeasonsData) JSON.deserializeStrict(jsonData, SeasonService.SeasonsData.class);

		// Construct a Unit Of Work to capture the follow working
		fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();

		Map<String, Driver__c> driversById = new Map<String, Driver__c>();
		for(DriverData driverData : seasonsData.drivers) {
		    // Create Driver__c record
			Driver__c driver = new Driver__c(
				Name = driverData.name,
				DriverId__c = driverData.driverId,
				Nationality__c = driverData.nationality,
				TwitterHandle__c = driverData.twitterHandle,
				FIA_Super_License__c = driverData.fiaLicense,
				Active__c = driverData.active);
			uow.registerNew(driver);
			driversById.put(driver.DriverId__c, driver);
		}
		Map<String, Team__c> teamsById = new Map<String, Team__c>();
		for(TeamData teamData : seasonsData.teams) {
			// Create Team__c record
			Team__c team = new Team__c(
				Name = teamData.name,
				Nationality__c = teamData.nationality,
				Home_Base__c = teamData.nationality,
				Active_Since__c = teamData.activeSince,
				Team_Boss__c = teamData.teamBoss,
				Team_Id__c = teamData.teamId
			);
			uow.registerNew(team);
			teamsById.put(team.Team_Id__c, team);
		}
		for(SeasonData seasonData : seasonsData.seasons) {
			// Create Season__c record
			Season__c season = new Season__c(
				Name = seasonData.year,
				Year__c = seasonData.year);
			uow.registerNew(season);
			for(RaceData raceData : seasonData.races) {
				// Create Race__c record
				Race__c race = new Race__c(
					Name = raceData.name,
					Round__c = raceData.round,
					Status__c = raceData.status,
					Race_Date__c = raceData.raceDate
					);				
				uow.registerNew(race, Race__c.Season__c, season);
				for(ContestantData contestantData : raceData.contestants) {
					// Create Contestant__c record
					Contestant__c contestant = new Contestant__c(
							Car_Number__c = contestantData.carNumber,
							Laps_Completed__c = Integer.valueOf(contestantData.lapsCompleted),
							ChampionshipPoints__c = contestantData.championshipPoints,
							DNF__c = contestantData.dnf,
							RacePosition__c = contestantData.racePosition,													
							Qualification1LapTime__c = contestantData.qualification1LapTime,
							Qualification2LapTime__c = contestantData.qualification2LapTime,
							Qualification3LapTime__c = contestantData.qualification3LapTime);
					uow.registerNew(contestant, Contestant__c.Race__c, race);
					uow.registerRelationship(contestant, 
						Contestant__c.Driver__c, driversById.get(contestantData.driverId));
					uow.registerRelationship(contestant, 
						Contestant__c.Team__c, teamsById.get(contestantData.teamId));
				}
			}
		}
		// Insert records registered with uow above
		uow.commitWork();
	}

	public class UpdateStandings {
		public Id seasonId;
		public Boolean issueNewsLetter;

	}

	public class SeasonsData {
		public List<DriverData> drivers;
		public List<TeamData> teams;
		public List<SeasonData> seasons;
	}

	public class DriverData {
		public String name;
		public String nationality;
		public String driverId;		
		public String twitterHandle;
		public Boolean fiaLicense;
		public Boolean active;		

	}

	public class TeamData {
		public string name;
		public string nationality;
		public string homeBase;
		public string activeSince;
		public string teamBoss;
		public string teamId;
	}

	public class SeasonData {
		public String year;
		public List<RaceData> races;
	}

	public class RaceData {
		public Integer round;
		public String name;
		public List<ContestantData> contestants;
	}

	public class ContestantData {
		public String driverId;
		public String teamId;
		public String carNumber;
		public String lapsCompleted;
		public Integer championshipPoints;
		public Boolean dnf;
		public Integer racePosition;
		public Integer qualification1LapTime;
		public Integer qualification2LapTime;
		public Integer qualification3LapTime;
	}

}