source/formulaforce/main/objects/Race__c/Race__c.object-meta.xml
<CustomObject>
    <label>Race</label>
    <nameField>
        <label>Race Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Races</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

source/formulaforce/main/objects/Race__c/fields/FastestLapBy__c.field-meta.xml
<CustomField>
    <fullName>FastestLapBy__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>deprecated - DO NOT USE</description>
    <label>Fastest Lap By (deprecated)</label>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Fastest Laps</relationshipLabel>
    <relationshipName>FastestLapByDriver</relationshipName>
    <type>Lookup</type>
</CustomField>

source/formulaforce/main/objects/Race__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status (deprecated)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Red Flagged</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

source/formulaforce/main/classes/FLSDemoController.cls
public with sharing class FLSDemoController {

    public Race__c Race {get;set;}

    public String Status { get { return Race.Status__c }}

    public String FastestLapBy { get { return Race.FastestLapBy__c}}

    public FLSDemoController() {
        Race = [SELECT Status__c, FastestLapBy__c FROM Race__c LIMIT 1];
    }

    @AuraEnabled
    public static Race__c getRace(Id raceId) {
        return [SELECT Status__c, FastestLapBy__c FROM Race WHERE Id = :raceId];
    }
}